name: weather_app_transy
description: Ung dung thoi tiet cho mon hoc Flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- Các thư viện theo yêu cầu bài tập ---
  
  # 1. Gọi API
  http: ^1.1.0
  
  # 2. Định dạng ngày tháng (VD: Thứ Hai, 12/12)
  intl: ^0.18.1
  
  # 3. Quản lý trạng thái (Provider)
  provider: ^6.1.1
  
  # 4. Lấy vị trí GPS và đổi tọa độ sang tên thành phố
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  
  # 5. Lưu dữ liệu offline (Cache)
  shared_preferences: ^2.2.2
  
  # 6. Load ảnh từ mạng mượt mà, tự lưu cache
  cached_network_image: ^3.3.0
  
  # 7. Kiểm tra kết nối mạng (Bonus trong bài tập)
  connectivity_plus: ^5.0.2

  # Icon của iOS/Android
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Chú ý: chữ 'assets' thụt vào 2 dấu cách so với 'flutter'
  # Dấu gạch đầu dòng '-' thụt vào 2 dấu cách so với 'assets'
  assets:
    - assets/images/